[build]
  command = "yarn build:production"
  publish = "/dist"
  base = "/"

[[redirects]]
  from = "/embed.js"
  to = "https://deploy-script.darass.co.kr/embed.js"
  status = 301


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200